// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApiConfig is a mock of ApiConfig interface.
type MockApiConfig struct {
	ctrl     *gomock.Controller
	recorder *MockApiConfigMockRecorder
}

// MockApiConfigMockRecorder is the mock recorder for MockApiConfig.
type MockApiConfigMockRecorder struct {
	mock *MockApiConfig
}

// NewMockApiConfig creates a new mock instance.
func NewMockApiConfig(ctrl *gomock.Controller) *MockApiConfig {
	mock := &MockApiConfig{ctrl: ctrl}
	mock.recorder = &MockApiConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiConfig) EXPECT() *MockApiConfigMockRecorder {
	return m.recorder
}

// GetFrontOrigin mocks base method.
func (m *MockApiConfig) GetFrontOrigin() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFrontOrigin")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFrontOrigin indicates an expected call of GetFrontOrigin.
func (mr *MockApiConfigMockRecorder) GetFrontOrigin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFrontOrigin", reflect.TypeOf((*MockApiConfig)(nil).GetFrontOrigin))
}
