// Code generated by MockGen. DO NOT EDIT.
// Source: bot.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBotConfig is a mock of BotConfig interface.
type MockBotConfig struct {
	ctrl     *gomock.Controller
	recorder *MockBotConfigMockRecorder
}

// MockBotConfigMockRecorder is the mock recorder for MockBotConfig.
type MockBotConfigMockRecorder struct {
	mock *MockBotConfig
}

// NewMockBotConfig creates a new mock instance.
func NewMockBotConfig(ctrl *gomock.Controller) *MockBotConfig {
	mock := &MockBotConfig{ctrl: ctrl}
	mock.recorder = &MockBotConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotConfig) EXPECT() *MockBotConfigMockRecorder {
	return m.recorder
}

// GetHelpPageURL mocks base method.
func (m *MockBotConfig) GetHelpPageURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelpPageURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHelpPageURL indicates an expected call of GetHelpPageURL.
func (mr *MockBotConfigMockRecorder) GetHelpPageURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelpPageURL", reflect.TypeOf((*MockBotConfig)(nil).GetHelpPageURL))
}
