@startuml
box "LINE" #LightGreen
  actor User1 as u1
  actor User2 as u2
  participant Group as lg
  actor Bot as b
end box

box "haraiai backend" #LightBlue
  participant Server as s
  database Database as d
end box

create lg
u1 -> lg: create group chat

u1 -> u2: invite to group
u2 -> lg: join to group chat

u1 -> b: invite to group
b -> lg: join to group chat

lg -> s: webhook: join event
s -> d: initialize group with empty members\nand CREATED group status.
b <- s: reply message:\n"Please tell me member names."
lg <-- b:

== group Initialization succeeded ==

u1 -> lg: tell user1 name.
lg -> s: webhook: message event
s -> d: add user1 to group members.
b <- s: reply message:\n"User1 added."
lg <-- b:


u2 -> lg: tell user2 name.
lg -> s: webhook: message event
s -> d: add user2 to group members\nand set READY group status.
b <- s: reply message:\n"User2, added."
lg <-- b:

== member registration succeeded ==

u1 -> lg: tell warikan information.
lg -> s: webhook: message event
s -> d: update pay amount of User1.
b <- s: reply message:\n"Updated."
lg <-- b:

...

u2 -> lg: request a tally of past payments
lg -> s: webhook: message event
s -> d: tally past payments
b <- s: reply message:\nabout pay amount of each user
lg <-- b:

@enduml
