// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/raahii/haraiai/pkg/client"
	"github.com/raahii/haraiai/pkg/messaging/config"
	"github.com/raahii/haraiai/pkg/messaging/flexmessage"
	"github.com/raahii/haraiai/pkg/messaging/handler"
	"github.com/raahii/haraiai/pkg/store"
)

// Injectors from wire.go:

func BuildBotHandler() (handler.BotHandler, error) {
	botConfig, err := config.ProvideBotConfig()
	if err != nil {
		return nil, err
	}
	botClient, err := client.ProvideBotClient()
	if err != nil {
		return nil, err
	}
	flexMessageBuilder := flexmessage.ProvideFlexMessageBuilder(botConfig)
	storeStore, err := store.ProvideStore()
	if err != nil {
		return nil, err
	}
	botHandler, err := handler.ProvideBotHandler(botConfig, botClient, flexMessageBuilder, storeStore)
	if err != nil {
		return nil, err
	}
	return botHandler, nil
}

// wire.go:

var mainSet = wire.NewSet(config.ProvideBotConfig, client.ProvideBotClient, store.ProvideStore, flexmessage.ProvideFlexMessageBuilder, handler.ProvideBotHandler)
